//! The GPU-independent authoritative world.
//!
//! `ServerWorld` owns simulation state, not transport.  It uses the existing
//! CPU voxel/entity primitives (which are also used by headless tests) and
//! never imports wgpu, winit, audio, camera, or UI modules.

use crate::authority::contract::{
    milli_to_vec3, position_to_milli_opt, RevisionClock, SessionFishingHookState,
    SessionGameplayState, SessionInventorySlot, WorldMutation,
};
use crate::authority::fishing::FishingDomainContext;
use crate::authority::interest::chunks_around;
use crate::authority::transactions::{self, WorkstationContext};
use crate::block_entity::{default_stub_for_block, BlockEntity, ContainerAccess};
use crate::chunk_manager::WorldColumns;
use crate::dimension::{generate_chunk_with_options, Dimension, WorldGenerationOptions};
use crate::entity::{Entity, EntityManager, EntityType};
use crate::fluid::FluidMutation;
use crate::game_rules::{Difficulty, WorldRules, WorldType};
use crate::inventory::ItemStack;
use crate::network::protocol::{
    GameplayOperation, GameplayRequest, ItemWire, PlayerId, RejectReason,
};
use crate::redstone::{RedstoneAction, RedstoneSystem};
use crate::save::{ChunkSaveData, EntitySaveData, MutationRevisionIndex};
use crate::world::{BlockType, chunk_origin, chunk_xz};
use glam::Vec3;
use rayon::prelude::*;
use std::collections::{BTreeMap, BTreeSet};

/// How missing columns are materialized.
///
/// `Sync` generates on the calling thread (tests / world construction).
/// `Async` only registers demand for the runtime worldgen worker; completed
/// columns are applied at the start of `AuthorityCore::tick`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WorldgenMode {
    Sync,
    Async,
}

const WORLD_BOUND: i32 = 30_000_000;
pub const FIXED_DT: f32 = 1.0 / 20.0;
/// Near-zero velocity gate shared with settled dropped-item physics skip.
const ENTITY_IDLE_VELOCITY_EPS: f32 = 1e-4;
/// Horizontal chase radius for the generic hostile velocity consumer.
/// Outside this range hostiles must not rewrite chase velocity every tick.
const HOSTILE_CHASE_RANGE: f32 = 40.0;
const MAX_AUTOMATION_TRANSFERS: usize = 64;
const MAX_FLUID_UPDATES: usize = 256;

/// All state required to advance one deterministic world tick.
pub struct ServerWorld {
    pub seed: u32,
    pub dimension: Dimension,
    pub world_type: WorldType,
    pub generate_structures: bool,
    pub rules: WorldRules,
    /// Server-owned difficulty shared by every loaded dimension.  It is kept
    /// outside `WorldRules` so adding this policy does not invalidate the
    /// existing binary level-save layout; `server.properties` is its durable
    /// source of truth.
    pub difficulty: Difficulty,
    pub time: u64,
    pub revisions: RevisionClock,
    pub chunks: WorldColumns,
    pub entities: EntityManager,
    pub redstone: RedstoneSystem,
    pub recipe_manager: crate::recipes::RecipeManager,
    pub container_viewers: BTreeMap<(i32, i32, i32), BTreeSet<PlayerId>>,
    /// Authoritative lifecycle intents emitted when a block-backed container
    /// is invalidated.  RuntimePresentation consumes these after the fixed
    /// tick and targets the exact player/dimension/position.
    pending_container_closures: Vec<ContainerClosure>,
    /// Extra revision-bearing mutations (for example the partner half of a
    /// double chest) generated by one gameplay request.
    pending_mutations: Vec<WorldMutation>,
    /// Redstone actions are drained after the world tick by AuthorityCore so
    /// globally unique entity ids can be assigned before execution.
    pending_redstone_actions: Vec<RedstoneAction>,
    /// Per-column block revision map. Evicting a column is O(that column).
    block_revisions: BTreeMap<(i32, i32), BTreeMap<(i32, i32, i32), u64>>,
    /// XOR of per-entry FNV-1a fingerprints for `block_revisions`.
    /// Maintained on insert/remove so idle ticks do not scan the map.
    block_revision_checksum: u64,
    chunk_revisions: BTreeMap<(i32, i32), u64>,
    /// Columns whose on-disk payload failed inflate/length checks. They are
    /// never inserted, generated, or written back so a later save cannot
    /// replace player builds with freshly generated terrain.
    failed_restore_chunks: BTreeSet<(i32, i32)>,
    /// Missing columns requested for async worldgen. Cleared when applied or
    /// when sync materialization inserts the column.
    pending_chunk_generation: BTreeSet<(i32, i32)>,
    worldgen_mode: WorldgenMode,
    /// Last `EntityManager::checksum_epoch` that was successfully persisted.
    /// Autosave skips `entities.dat` while this matches the live epoch.
    entities_persisted_epoch: u64,
    /// Pressure-plate occupants rebuilt only when a player crosses a column.
    plate_occupants: Vec<(i32, i32, i32)>,
    /// Column key `(player_id, cx, cz)` that last built `plate_occupants`.
    plate_occupant_columns: Vec<(PlayerId, i32, i32)>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ContainerClosure {
    pub player_id: PlayerId,
    pub dimension: Dimension,
    pub position: (i32, i32, i32),
}


mod columns;
mod containers;
mod entities;
mod mutation;
mod tick;

#[cfg(test)]
mod tests;

