use crate::brewing::{PotionData, PotionKind};
use crate::enchantment::{Enchantment, EnchantmentSet};
use crate::inventory::{Item, ItemStack};
use serde::{Deserialize, Serialize};

/// Request identifiers are generated by the client and are scoped to an
/// authenticated session.  A server keeps a bounded response cache keyed by
/// this value so retransmits are idempotent.
pub type RequestId = u128;
pub type ServerSequence = u64;

pub const MAX_REQUEST_BYTES: usize = 16 * 1024;
pub const MAX_REQUEST_STRING_BYTES: usize = 256;
pub const MAX_COMMAND_BYTES: usize = 2 * 1024;
pub const SESSION_SLOT_COUNT: u8 = 41;
pub const MAX_CONTAINER_SLOTS: u16 = 54;
pub const MAX_ANVIL_RENAME_BYTES: usize = 24;
pub const MAX_BLOCK_COORDINATE: i32 = 30_000_000;
pub const MIN_BLOCK_Y: i32 = -64;
pub const MAX_BLOCK_Y: i32 = 319;
pub const MAX_SESSION_VELOCITY_MILLI: i32 = 1_000_000;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RejectReason {
    Unauthorized,
    Duplicate,
    OutOfOrder,
    InvalidDimension,
    InvalidRevision,
    TooFar,
    InvalidCoordinate,
    PermissionDenied,
    RateLimited,
    QueueFull,
    Malformed,
    StringTooLong,
    Unsupported,
    InvalidState,
}


/// Stable wire mapping for container open/close. Click uses
/// `GameplayOperation::ContainerClick`. Unknown discriminants fail decode.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[repr(u8)]
pub enum ContainerAction {
    Open = 0,
    Close = 1,
}

/// Metadata-preserving authority inventory value. The fixed-width Adventure
/// masks keep the request bounded while retaining the identity fields that
/// participate in exact transaction comparisons.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct SessionSlotWire {
    pub item: ItemWire,
    pub can_break: u128,
    pub can_place_on: u128,
}

impl SessionSlotWire {
    pub const fn new(item: ItemWire, can_break: u128, can_place_on: u128) -> Self {
        Self {
            item,
            can_break,
            can_place_on,
        }
    }

    pub fn same_identity(self, other: Self) -> bool {
        self.item.item == other.item.item
            && self.item.durability == other.item.durability
            && self.item.enchantments == other.item.enchantments
            && self.item.potion == other.item.potion
            && self.item.custom_name == other.item.custom_name
            && self.can_break == other.can_break
            && self.can_place_on == other.can_place_on
    }

    pub fn validate_bounds(&self) -> Result<(), RejectReason> {
        self.item.validate_rich_bounds(false)
    }
}

/// Exact source reference used by atomic authority transactions. `expected`
/// prevents a delayed request from consuming a different stack after the same
/// inventory index has changed; `count` is the requested debit from that stack.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct SlotRefWire {
    pub index: u8,
    pub count: u16,
    pub expected: SessionSlotWire,
}

impl SlotRefWire {
    pub fn validate_bounds(&self) -> Result<(), RejectReason> {
        if self.index >= SESSION_SLOT_COUNT
            || self.count == 0
            || self.count > self.expected.item.count
        {
            return Err(RejectReason::InvalidState);
        }
        self.expected.validate_bounds()
    }
}

/// Fixed-width fishing projection for one authoritative session. Coordinates
/// are milliblocks so the packet stays deterministic and free of float edge
/// cases.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct SessionFishingHookWire {
    pub entity_id: u64,
    pub position_milli: [i32; 3],
    pub velocity_milli: [i32; 3],
    pub stage: u8,
    pub wait_ticks_remaining: u32,
    pub bite_ticks_remaining: u32,
}

/// Bounded in-flight brew projection. Source references retain exact rich item
/// identity and the three bottle positions are fixed-width.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct SessionBrewWire {
    pub station: [i32; 3],
    pub ingredient: SlotRefWire,
    pub bottles: [Option<SlotRefWire>; 3],
    pub remaining_ticks: u16,
}

/// Owner-private fixed-tick mining projection. Coordinates and progress are
/// integer-bounded so a client cannot allocate or inject floating-point state
/// at the authority boundary.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct MiningProgressWire {
    pub dimension: u8,
    pub target: [i32; 3],
    pub progress_milli: u16,
    pub hand: u8,
    /// Latched inventory index (main-hand hotbar slot or offhand index 40).
    pub slot_index: u8,
    pub held: Option<SessionSlotWire>,
    /// Expected block/state captured when StartBreak was accepted. A changed
    /// world value cancels the owner-private progress instead of mining a new
    /// block under a stale request.
    pub block: u32,
    pub state: u8,
    pub look_milli: [i16; 3],
}

impl Default for MiningProgressWire {
    fn default() -> Self {
        Self {
            dimension: 0,
            target: [0; 3],
            progress_milli: 0,
            hand: 0,
            slot_index: 0,
            held: None,
            block: crate::world::BlockType::Air.to_wire(),
            state: 0,
            look_milli: [0, 1_000, 0],
        }
    }
}

/// Complete private session projection. The inventory is a fixed 41-slot
/// array, preventing an authority snapshot from creating attacker-controlled
/// allocations at the transport boundary.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct SessionGameplayWire {
    pub health_milli: u32,
    pub max_health_milli: u32,
    pub hunger_milli: u32,
    pub saturation_milli: u32,
    pub is_dead: bool,
    pub death_source: Option<u8>,
    pub invulnerability_ticks: u16,
    pub velocity_milli: [i32; 3],
    pub experience: u32,
    pub experience_level: u32,
    pub selected_hotbar_slot: u8,
    pub hotbar: [Option<SessionSlotWire>; 9],
    pub main: [Option<SessionSlotWire>; 27],
    pub armor: [Option<SessionSlotWire>; 4],
    pub offhand: Option<SessionSlotWire>,
    pub mounted_entity: Option<u64>,
    pub attack_cooldown_ticks: u16,
    pub shield_active: bool,
    pub shield_cooldown_ticks: u16,
    pub enchant_seed: u64,
    pub fishing_hook: Option<SessionFishingHookWire>,
    pub brew: Option<SessionBrewWire>,
    /// Active mining is private to the owner; observers never receive another
    /// player's progress through this session projection.
    #[serde(default)]
    pub mining: Option<MiningProgressWire>,
    pub revision: u64,
}

impl Default for SessionGameplayWire {
    fn default() -> Self {
        Self {
            health_milli: 20_000,
            max_health_milli: 20_000,
            hunger_milli: 20_000,
            saturation_milli: 5_000,
            is_dead: false,
            death_source: None,
            invulnerability_ticks: 0,
            velocity_milli: [0; 3],
            experience: 0,
            experience_level: 0,
            selected_hotbar_slot: 0,
            hotbar: [None; 9],
            main: [None; 27],
            armor: [None; 4],
            offhand: None,
            mounted_entity: None,
            attack_cooldown_ticks: 5,
            shield_active: false,
            shield_cooldown_ticks: 0,
            enchant_seed: 0,
            fishing_hook: None,
            brew: None,
            mining: None,
            revision: 0,
        }
    }
}

impl SessionGameplayWire {
    pub fn validate_bounds(&self) -> Result<(), RejectReason> {
        if self.max_health_milli == 0
            || self.health_milli > self.max_health_milli
            || self.hunger_milli > 20_000
            || self.saturation_milli > self.hunger_milli
            || self.selected_hotbar_slot >= 9
            || self
                .velocity_milli
                .iter()
                .any(|component| component.unsigned_abs() > MAX_SESSION_VELOCITY_MILLI as u32)
        {
            return Err(RejectReason::InvalidState);
        }
        for slot in self
            .hotbar
            .iter()
            .chain(self.main.iter())
            .chain(self.armor.iter())
            .chain(std::iter::once(&self.offhand))
            .flatten()
        {
            slot.validate_bounds()?;
        }
        if let Some(brew) = self.brew {
            validate_coordinate(brew.station[0], brew.station[1], brew.station[2])?;
            brew.ingredient.validate_bounds()?;
            for bottle in brew.bottles.iter().flatten() {
                bottle.validate_bounds()?;
            }
        }
        if let Some(mining) = self.mining {
            if mining.dimension > 2
                || mining.progress_milli > 1_000
                || mining.hand > 1
                || mining.slot_index >= SESSION_SLOT_COUNT
                || (mining.hand == 1 && mining.slot_index != 40)
                || (mining.hand == 0 && mining.slot_index >= 9)
                || crate::world::BlockType::from_wire(mining.block).is_none()
                || !valid_look(mining.look_milli)
            {
                return Err(RejectReason::InvalidState);
            }
            validate_coordinate(mining.target[0], mining.target[1], mining.target[2])?;
            if let Some(held) = mining.held {
                held.validate_bounds()?;
            }
        }
        Ok(())
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct PotionWire {
    pub kind: u8,
    pub level: u8,
    pub duration_seconds: u16,
    pub splash: bool,
}

impl PotionWire {
    pub fn from_potion(data: PotionData) -> Self {
        let kind = match data.kind {
            PotionKind::Water => 0,
            PotionKind::Awkward => 1,
            PotionKind::Speed => 2,
            PotionKind::Strength => 3,
            PotionKind::Healing => 4,
            PotionKind::Regeneration => 5,
            PotionKind::NightVision => 6,
            PotionKind::Invisibility => 7,
            PotionKind::FireResistance => 8,
            PotionKind::WaterBreathing => 9,
            PotionKind::Poison => 10,
            PotionKind::Slowness => 11,
        };
        Self {
            kind,
            level: data.level,
            duration_seconds: data.duration_seconds,
            splash: data.splash,
        }
    }

    pub fn to_potion(&self) -> Option<PotionData> {
        let kind = match self.kind {
            0 => PotionKind::Water,
            1 => PotionKind::Awkward,
            2 => PotionKind::Speed,
            3 => PotionKind::Strength,
            4 => PotionKind::Healing,
            5 => PotionKind::Regeneration,
            6 => PotionKind::NightVision,
            7 => PotionKind::Invisibility,
            8 => PotionKind::FireResistance,
            9 => PotionKind::WaterBreathing,
            10 => PotionKind::Poison,
            11 => PotionKind::Slowness,
            _ => return None,
        };
        Some(PotionData {
            kind,
            level: self.level,
            duration_seconds: self.duration_seconds,
            splash: self.splash,
        })
    }
}

pub(super) fn enc_to_u8(enc: &Enchantment) -> u8 {
    let kind = match enc {
        Enchantment::Efficiency(_) => 0,
        Enchantment::Unbreaking(_) => 1,
        Enchantment::SilkTouch => 2,
        Enchantment::Fortune(_) => 3,
        Enchantment::Sharpness(_) => 4,
        Enchantment::Knockback(_) => 5,
        Enchantment::FireAspect(_) => 6,
        Enchantment::Looting(_) => 7,
        Enchantment::Protection(_) => 8,
        Enchantment::FeatherFalling(_) => 9,
        Enchantment::Respiration(_) => 10,
        Enchantment::Power(_) => 11,
        Enchantment::Infinity => 12,
    };
    let lvl = enc.level().max(1);
    ((kind + 1) << 4) | (lvl & 0x0F)
}

pub(super) fn enc_from_u8(b: u8) -> Option<Enchantment> {
    if b == 0 {
        return None;
    }
    let kind_code = (b >> 4).checked_sub(1)?;
    let lvl = b & 0x0F;
    if lvl == 0 {
        return None;
    }
    match kind_code {
        0 => Some(Enchantment::Efficiency(lvl)),
        1 => Some(Enchantment::Unbreaking(lvl)),
        2 => Some(Enchantment::SilkTouch),
        3 => Some(Enchantment::Fortune(lvl)),
        4 => Some(Enchantment::Sharpness(lvl)),
        5 => Some(Enchantment::Knockback(lvl)),
        6 => Some(Enchantment::FireAspect(lvl)),
        7 => Some(Enchantment::Looting(lvl)),
        8 => Some(Enchantment::Protection(lvl)),
        9 => Some(Enchantment::FeatherFalling(lvl)),
        10 => Some(Enchantment::Respiration(lvl)),
        11 => Some(Enchantment::Power(lvl)),
        12 => Some(Enchantment::Infinity),
        _ => None,
    }
}

fn max_enchantment_level(enchantment: Enchantment) -> u8 {
    match enchantment {
        Enchantment::Efficiency(_) | Enchantment::Sharpness(_) | Enchantment::Power(_) => 5,
        Enchantment::Protection(_) | Enchantment::FeatherFalling(_) => 4,
        Enchantment::Unbreaking(_)
        | Enchantment::Fortune(_)
        | Enchantment::Looting(_)
        | Enchantment::Respiration(_) => 3,
        Enchantment::Knockback(_) | Enchantment::FireAspect(_) => 2,
        Enchantment::SilkTouch | Enchantment::Infinity => 1,
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct ItemWire {
    pub item: u32,
    pub count: u16,
    pub durability: u16,
    pub enchantments: [u8; 6],
    pub potion: Option<PotionWire>,
    pub custom_name: [u8; 24],
    /// Adventure-mode metadata retained for automation entity projection.
    #[serde(default)]
    pub can_break: u128,
    #[serde(default)]
    pub can_place_on: u128,
}

impl ItemWire {
    pub fn empty() -> Self {
        Self {
            item: Item::Air as u32,
            count: 0,
            durability: 0,
            enchantments: [0; 6],
            potion: None,
            custom_name: [0; 24],
            can_break: 0,
            can_place_on: 0,
        }
    }

    pub fn from_stack(stack: &ItemStack) -> Self {
        if stack.count == 0 || stack.item == Item::Air {
            return Self::empty();
        }
        let mut enchantments = [0u8; 6];
        for (i, entry) in stack.enchantments.entries.iter().enumerate() {
            if i < 6 {
                if let Some(enc) = entry {
                    enchantments[i] = enc_to_u8(enc);
                }
            }
        }
        let potion = stack.potion.map(PotionWire::from_potion);
        let mut custom_name = [0u8; 24];
        let name_bytes = stack.custom_name.as_str().as_bytes();
        let len = name_bytes.len().min(24);
        custom_name[..len].copy_from_slice(&name_bytes[..len]);

        Self {
            item: stack.item.to_u32(),
            count: stack.count as u16,
            durability: stack.durability as u16,
            enchantments,
            potion,
            custom_name,
            can_break: stack.can_break,
            can_place_on: stack.can_place_on,
        }
    }

    pub fn to_stack(&self) -> Option<ItemStack> {
        if self.count == 0 {
            return None;
        }
        let item = Item::from_u32(self.item)?;
        if item == Item::Air {
            return None;
        }
        let mut stack = ItemStack::new(item, self.count as u32);
        stack.durability = self.durability as u32;
        let mut enc_set = EnchantmentSet::default();
        for &b in &self.enchantments {
            if let Some(enc) = enc_from_u8(b) {
                enc_set.add_or_upgrade(enc);
            }
        }
        stack.enchantments = enc_set;
        if let Some(pw) = self.potion {
            stack.potion = pw.to_potion();
        }
        let name_str = std::str::from_utf8(&self.custom_name)
            .unwrap_or("")
            .trim_matches('\0');
        if !name_str.is_empty() {
            stack.custom_name.set(name_str);
        }
        stack.can_break = self.can_break;
        stack.can_place_on = self.can_place_on;
        Some(stack)
    }

    /// Validate a metadata-rich stack before it can participate in an
    /// authoritative transaction. Empty is permitted only for legacy cursor
    /// projections; source references must always name a concrete stack.
    pub fn validate_rich_bounds(&self, allow_empty: bool) -> Result<(), RejectReason> {
        if self.count == 0 {
            return if allow_empty && *self == Self::empty() {
                Ok(())
            } else {
                Err(RejectReason::InvalidState)
            };
        }
        validate_item_count(self.item, self.count)?;
        for value in self
            .enchantments
            .iter()
            .copied()
            .filter(|value| *value != 0)
        {
            let Some(enchantment) = enc_from_u8(value) else {
                return Err(RejectReason::Malformed);
            };
            if enchantment.level() > max_enchantment_level(enchantment)
                || enc_to_u8(&enchantment) != value
            {
                return Err(RejectReason::Malformed);
            }
        }
        if self
            .potion
            .is_some_and(|potion| potion.to_potion().is_none())
        {
            return Err(RejectReason::Malformed);
        }
        let name_end = self
            .custom_name
            .iter()
            .position(|byte| *byte == 0)
            .unwrap_or(self.custom_name.len());
        if self.custom_name[name_end..].iter().any(|byte| *byte != 0)
            || std::str::from_utf8(&self.custom_name[..name_end]).is_err()
        {
            return Err(RejectReason::Malformed);
        }
        let canonical = self
            .to_stack()
            .map(|stack| Self::from_stack(&stack))
            .ok_or(RejectReason::Malformed)?;
        if canonical != *self {
            return Err(RejectReason::Malformed);
        }
        Ok(())
    }
}

pub(super) fn validate_coordinate(x: i32, y: i32, z: i32) -> Result<(), RejectReason> {
    if x.unsigned_abs() > MAX_BLOCK_COORDINATE as u32
        || z.unsigned_abs() > MAX_BLOCK_COORDINATE as u32
        || !(MIN_BLOCK_Y..=MAX_BLOCK_Y).contains(&y)
    {
        Err(RejectReason::InvalidCoordinate)
    } else {
        Ok(())
    }
}

pub(super) fn validate_item_count(item: u32, count: u16) -> Result<(), RejectReason> {
    let Some(item) = Item::from_u32(item) else {
        return Err(RejectReason::Malformed);
    };
    let max_stack = item.properties().max_stack.min(u32::from(u16::MAX));
    if item == Item::Air || count == 0 || u32::from(count) > max_stack {
        Err(RejectReason::InvalidState)
    } else {
        Ok(())
    }
}

pub(super) fn validate_slot_refs<'a>(
    refs: impl IntoIterator<Item = &'a SlotRefWire>,
) -> Result<(), RejectReason> {
    let mut expected = [None; SESSION_SLOT_COUNT as usize];
    let mut totals = [0u32; SESSION_SLOT_COUNT as usize];
    for source in refs {
        source.validate_bounds()?;
        let index = usize::from(source.index);
        if expected[index].is_some_and(|slot| slot != source.expected) {
            return Err(RejectReason::InvalidState);
        }
        expected[index] = Some(source.expected);
        totals[index] = totals[index]
            .checked_add(u32::from(source.count))
            .ok_or(RejectReason::InvalidState)?;
        if totals[index] > u32::from(source.expected.item.count) {
            return Err(RejectReason::InvalidState);
        }
    }
    Ok(())
}

pub(super) fn valid_look(look_milli: [i16; 3]) -> bool {
    let length_squared = look_milli
        .iter()
        .map(|component| i64::from(*component) * i64::from(*component))
        .sum::<i64>();
    (250_000..=1_210_000).contains(&length_squared)
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum GameplayOutcome {
    Accepted { revision: u64 },
    Rejected { reason: RejectReason },
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct GameplayResponse {
    pub request_id: RequestId,
    pub server_sequence: ServerSequence,
    pub outcome: GameplayOutcome,
}
