//! Static per-discriminant item definition table (Plan 21).
//! Indexed by Item as usize. Values are byte-identical to the former match arms.

use super::{
    ArmorProperties, ArmorSlot, CreativeTab, FoodProperties, Item, ToolMaterial, ToolProperties,
    ToolType,
};
use crate::world::BlockType;

pub const ITEM_COUNT: usize = Item::Observer as usize + 1;

#[derive(Debug, Clone, Copy)]
pub struct ItemDef {
    pub name: &'static str,
    pub max_stack: u32,
    pub is_block: bool,
    pub block_type: Option<BlockType>,
    pub tex_coords: (u32, u32),
    pub creative_tab: Option<CreativeTab>,
    pub tool: Option<ToolProperties>,
    pub armor: Option<ArmorProperties>,
    pub food: Option<FoodProperties>,
}

pub static ITEM_DEFS: [ItemDef; ITEM_COUNT] = [
    // Air = 0
    ItemDef {
        name: "Air",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (0, 0),
        creative_tab: None,
        tool: None,
        armor: None,
        food: None,
    },
    // Grass = 1
    ItemDef {
        name: "Grass Block",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Grass),
        tex_coords: (1, 0),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // Dirt = 2
    ItemDef {
        name: "Dirt",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Dirt),
        tex_coords: (2, 0),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // Stone = 3
    ItemDef {
        name: "Stone",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Stone),
        tex_coords: (3, 0),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // Sand = 4
    ItemDef {
        name: "Sand",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Sand),
        tex_coords: (4, 0),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // Gravel = 5
    ItemDef {
        name: "Gravel",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Gravel),
        tex_coords: (5, 0),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // OakLog = 6
    ItemDef {
        name: "Oak Log",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::OakLog),
        tex_coords: (11, 1),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // OakPlanks = 7
    ItemDef {
        name: "Oak Planks",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::OakPlanks),
        tex_coords: (6, 0),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // OakLeaves = 8
    ItemDef {
        name: "Oak Leaves",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::OakLeaves),
        tex_coords: (7, 0),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // Cobblestone = 9
    ItemDef {
        name: "Cobblestone",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Cobblestone),
        tex_coords: (8, 0),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // Bedrock = 10
    ItemDef {
        name: "Bedrock",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Bedrock),
        tex_coords: (9, 0),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // Water = 11
    ItemDef {
        name: "Water",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Water),
        tex_coords: (10, 0),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // CoalOre = 12
    ItemDef {
        name: "Coal Ore",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::CoalOre),
        tex_coords: (11, 0),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // IronOre = 13
    ItemDef {
        name: "Iron Ore",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::IronOre),
        tex_coords: (12, 0),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // GoldOre = 14
    ItemDef {
        name: "Gold Ore",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::GoldOre),
        tex_coords: (13, 0),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // DiamondOre = 15
    ItemDef {
        name: "Diamond Ore",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::DiamondOre),
        tex_coords: (14, 0),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // RedstoneOre = 16
    ItemDef {
        name: "Redstone Ore",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::RedstoneOre),
        tex_coords: (15, 0),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // Glass = 17
    ItemDef {
        name: "Glass",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Glass),
        tex_coords: (0, 1),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // Brick = 18
    ItemDef {
        name: "Brick Block",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Brick),
        tex_coords: (1, 1),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // StoneBrick = 19
    ItemDef {
        name: "Stone Brick",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::StoneBrick),
        tex_coords: (2, 1),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // Snow = 20
    ItemDef {
        name: "Snow Block",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Snow),
        tex_coords: (4, 1),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // Ice = 21
    ItemDef {
        name: "Ice",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Ice),
        tex_coords: (5, 1),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // Clay = 22
    ItemDef {
        name: "Clay Block",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Clay),
        tex_coords: (6, 1),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // Sandstone = 23
    ItemDef {
        name: "Sandstone",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Sandstone),
        tex_coords: (8, 1),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // Obsidian = 24
    ItemDef {
        name: "Obsidian",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Obsidian),
        tex_coords: (9, 1),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // CraftingTable = 25
    ItemDef {
        name: "Crafting Table",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::CraftingTable),
        tex_coords: (13, 1),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // Furnace = 26
    ItemDef {
        name: "Furnace",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Furnace),
        tex_coords: (14, 1),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // Chest = 27
    ItemDef {
        name: "Chest",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Chest),
        tex_coords: (15, 1),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // TNT = 28
    ItemDef {
        name: "TNT",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::TNT),
        tex_coords: (2, 2),
        creative_tab: Some(CreativeTab::Redstone),
        tool: None,
        armor: None,
        food: None,
    },
    // Bookshelf = 29
    ItemDef {
        name: "Bookshelf",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Bookshelf),
        tex_coords: (3, 2),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // Torch = 30
    ItemDef {
        name: "Torch",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Torch),
        tex_coords: (4, 2),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // Lava = 31
    ItemDef {
        name: "Lava",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Lava),
        tex_coords: (15, 2),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // Bed = 32
    ItemDef {
        name: "Bed",
        max_stack: 1,
        is_block: true,
        block_type: Some(BlockType::Bed),
        tex_coords: (6, 0),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // StoneSword = 33
    ItemDef {
        name: "Stone Sword",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (0, 4),
        creative_tab: Some(CreativeTab::Combat),
        tool: Some(ToolProperties {
            tool_type: ToolType::Sword,
            material: ToolMaterial::Stone,
            mining_speed: 4f32,
            durability: 131,
            damage: 5f32,
        }),
        armor: None,
        food: None,
    },
    // StonePickaxe = 34
    ItemDef {
        name: "Stone Pickaxe",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (0, 5),
        creative_tab: Some(CreativeTab::Tools),
        tool: Some(ToolProperties {
            tool_type: ToolType::Pickaxe,
            material: ToolMaterial::Stone,
            mining_speed: 4f32,
            durability: 131,
            damage: 3f32,
        }),
        armor: None,
        food: None,
    },
    // StoneAxe = 35
    ItemDef {
        name: "Stone Axe",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (0, 6),
        creative_tab: Some(CreativeTab::Tools),
        tool: Some(ToolProperties {
            tool_type: ToolType::Axe,
            material: ToolMaterial::Stone,
            mining_speed: 4f32,
            durability: 131,
            damage: 4f32,
        }),
        armor: None,
        food: None,
    },
    // StoneShovel = 36
    ItemDef {
        name: "Stone Shovel",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (0, 7),
        creative_tab: Some(CreativeTab::Tools),
        tool: Some(ToolProperties {
            tool_type: ToolType::Shovel,
            material: ToolMaterial::Stone,
            mining_speed: 4f32,
            durability: 131,
            damage: 2f32,
        }),
        armor: None,
        food: None,
    },
    // IronSword = 37
    ItemDef {
        name: "Iron Sword",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (1, 4),
        creative_tab: Some(CreativeTab::Combat),
        tool: Some(ToolProperties {
            tool_type: ToolType::Sword,
            material: ToolMaterial::Iron,
            mining_speed: 6f32,
            durability: 250,
            damage: 6f32,
        }),
        armor: None,
        food: None,
    },
    // IronPickaxe = 38
    ItemDef {
        name: "Iron Pickaxe",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (1, 5),
        creative_tab: Some(CreativeTab::Tools),
        tool: Some(ToolProperties {
            tool_type: ToolType::Pickaxe,
            material: ToolMaterial::Iron,
            mining_speed: 6f32,
            durability: 250,
            damage: 4f32,
        }),
        armor: None,
        food: None,
    },
    // IronAxe = 39
    ItemDef {
        name: "Iron Axe",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (1, 6),
        creative_tab: Some(CreativeTab::Tools),
        tool: Some(ToolProperties {
            tool_type: ToolType::Axe,
            material: ToolMaterial::Iron,
            mining_speed: 6f32,
            durability: 250,
            damage: 5f32,
        }),
        armor: None,
        food: None,
    },
    // IronShovel = 40
    ItemDef {
        name: "Iron Shovel",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (1, 7),
        creative_tab: Some(CreativeTab::Tools),
        tool: Some(ToolProperties {
            tool_type: ToolType::Shovel,
            material: ToolMaterial::Iron,
            mining_speed: 6f32,
            durability: 250,
            damage: 3f32,
        }),
        armor: None,
        food: None,
    },
    // DiamondSword = 41
    ItemDef {
        name: "Diamond Sword",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (2, 4),
        creative_tab: Some(CreativeTab::Combat),
        tool: Some(ToolProperties {
            tool_type: ToolType::Sword,
            material: ToolMaterial::Diamond,
            mining_speed: 8f32,
            durability: 1561,
            damage: 7f32,
        }),
        armor: None,
        food: None,
    },
    // DiamondPickaxe = 42
    ItemDef {
        name: "Diamond Pickaxe",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (2, 5),
        creative_tab: Some(CreativeTab::Tools),
        tool: Some(ToolProperties {
            tool_type: ToolType::Pickaxe,
            material: ToolMaterial::Diamond,
            mining_speed: 8f32,
            durability: 1561,
            damage: 5f32,
        }),
        armor: None,
        food: None,
    },
    // DiamondAxe = 43
    ItemDef {
        name: "Diamond Axe",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (2, 6),
        creative_tab: Some(CreativeTab::Tools),
        tool: Some(ToolProperties {
            tool_type: ToolType::Axe,
            material: ToolMaterial::Diamond,
            mining_speed: 8f32,
            durability: 1561,
            damage: 6f32,
        }),
        armor: None,
        food: None,
    },
    // DiamondShovel = 44
    ItemDef {
        name: "Diamond Shovel",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (2, 7),
        creative_tab: Some(CreativeTab::Tools),
        tool: Some(ToolProperties {
            tool_type: ToolType::Shovel,
            material: ToolMaterial::Diamond,
            mining_speed: 8f32,
            durability: 1561,
            damage: 4f32,
        }),
        armor: None,
        food: None,
    },
    // WoodenHoe = 45
    ItemDef {
        name: "Wooden Hoe",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (0, 8),
        creative_tab: Some(CreativeTab::Tools),
        tool: Some(ToolProperties {
            tool_type: ToolType::Hoe,
            material: ToolMaterial::Wood,
            mining_speed: 2f32,
            durability: 59,
            damage: 1f32,
        }),
        armor: None,
        food: None,
    },
    // StoneHoe = 46
    ItemDef {
        name: "Stone Hoe",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (1, 8),
        creative_tab: Some(CreativeTab::Tools),
        tool: Some(ToolProperties {
            tool_type: ToolType::Hoe,
            material: ToolMaterial::Stone,
            mining_speed: 4f32,
            durability: 131,
            damage: 1f32,
        }),
        armor: None,
        food: None,
    },
    // IronHoe = 47
    ItemDef {
        name: "Iron Hoe",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (2, 8),
        creative_tab: Some(CreativeTab::Tools),
        tool: Some(ToolProperties {
            tool_type: ToolType::Hoe,
            material: ToolMaterial::Iron,
            mining_speed: 6f32,
            durability: 250,
            damage: 1f32,
        }),
        armor: None,
        food: None,
    },
    // GoldenHoe = 48
    ItemDef {
        name: "Golden Hoe",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (4, 8),
        creative_tab: Some(CreativeTab::Tools),
        tool: Some(ToolProperties {
            tool_type: ToolType::Hoe,
            material: ToolMaterial::Gold,
            mining_speed: 12f32,
            durability: 32,
            damage: 1f32,
        }),
        armor: None,
        food: None,
    },
    // DiamondHoe = 49
    ItemDef {
        name: "Diamond Hoe",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (3, 8),
        creative_tab: Some(CreativeTab::Tools),
        tool: Some(ToolProperties {
            tool_type: ToolType::Hoe,
            material: ToolMaterial::Diamond,
            mining_speed: 8f32,
            durability: 1561,
            damage: 1f32,
        }),
        armor: None,
        food: None,
    },
    // Stick = 50
    ItemDef {
        name: "Stick",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (0, 3),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // Coal = 51
    ItemDef {
        name: "Coal",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (1, 3),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // IronIngot = 52
    ItemDef {
        name: "Iron Ingot",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (2, 3),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // GoldIngot = 53
    ItemDef {
        name: "Gold Ingot",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (3, 3),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // Diamond = 54
    ItemDef {
        name: "Diamond",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (4, 3),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // Redstone = 55
    ItemDef {
        name: "Redstone Dust",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (5, 3),
        creative_tab: Some(CreativeTab::Redstone),
        tool: None,
        armor: None,
        food: None,
    },
    // BoneMeal = 56
    ItemDef {
        name: "Bone Meal",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (15, 10),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // Apple = 57
    ItemDef {
        name: "Apple",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (6, 3),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: Some(FoodProperties {
            hunger: 4f32,
            saturation: 2.4f32,
            use_duration_ticks: 32,
            always_edible: false,
            return_item: None,
        }),
    },
    // Bread = 58
    ItemDef {
        name: "Bread",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (7, 3),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: Some(FoodProperties {
            hunger: 5f32,
            saturation: 6f32,
            use_duration_ticks: 32,
            always_edible: false,
            return_item: None,
        }),
    },
    // Potato = 59
    ItemDef {
        name: "Potato",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::PotatoCrop),
        tex_coords: (15, 3),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: Some(FoodProperties {
            hunger: 1f32,
            saturation: 0.6f32,
            use_duration_ticks: 32,
            always_edible: false,
            return_item: None,
        }),
    },
    // BakedPotato = 60
    ItemDef {
        name: "Baked Potato",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (7, 11),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: Some(FoodProperties {
            hunger: 5f32,
            saturation: 6f32,
            use_duration_ticks: 32,
            always_edible: false,
            return_item: None,
        }),
    },
    // PoisonousPotato = 61
    ItemDef {
        name: "Poisonous Potato",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (8, 11),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: Some(FoodProperties {
            hunger: 2f32,
            saturation: 1.2f32,
            use_duration_ticks: 32,
            always_edible: false,
            return_item: None,
        }),
    },
    // GoldenApple = 62
    ItemDef {
        name: "Golden Apple",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (11, 0),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: Some(FoodProperties {
            hunger: 4f32,
            saturation: 9.6f32,
            use_duration_ticks: 32,
            always_edible: true,
            return_item: None,
        }),
    },
    // RottenFlesh = 63
    ItemDef {
        name: "Rotten Flesh",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (8, 3),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: Some(FoodProperties {
            hunger: 4f32,
            saturation: 0.8f32,
            use_duration_ticks: 32,
            always_edible: false,
            return_item: None,
        }),
    },
    // Bone = 64
    ItemDef {
        name: "Bone",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (9, 3),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // Bow = 65
    ItemDef {
        name: "Bow",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (10, 3),
        creative_tab: Some(CreativeTab::Combat),
        tool: None,
        armor: None,
        food: None,
    },
    // Gunpowder = 66
    ItemDef {
        name: "Gunpowder",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (11, 3),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: None,
    },
    // Wheat = 67
    ItemDef {
        name: "Wheat",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (12, 3),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: None,
    },
    // Seeds = 68
    ItemDef {
        name: "Seeds",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::WheatCrop),
        tex_coords: (13, 3),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // Carrot = 69
    ItemDef {
        name: "Carrot",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::CarrotCrop),
        tex_coords: (14, 3),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: Some(FoodProperties {
            hunger: 3f32,
            saturation: 3.6f32,
            use_duration_ticks: 32,
            always_edible: false,
            return_item: None,
        }),
    },
    // Shears = 70
    ItemDef {
        name: "Shears",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (0, 11),
        creative_tab: Some(CreativeTab::Tools),
        tool: Some(ToolProperties {
            tool_type: ToolType::None,
            material: ToolMaterial::Iron,
            mining_speed: 1f32,
            durability: 238,
            damage: 1f32,
        }),
        armor: None,
        food: None,
    },
    // Bucket = 71
    ItemDef {
        name: "Bucket",
        max_stack: 16,
        is_block: false,
        block_type: None,
        tex_coords: (1, 11),
        creative_tab: Some(CreativeTab::Tools),
        tool: None,
        armor: None,
        food: None,
    },
    // MilkBucket = 72
    ItemDef {
        name: "Milk Bucket",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (2, 11),
        creative_tab: Some(CreativeTab::Tools),
        tool: None,
        armor: None,
        food: None,
    },
    // RawPorkchop = 73
    ItemDef {
        name: "Raw Porkchop",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (3, 11),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: Some(FoodProperties {
            hunger: 3f32,
            saturation: 1.8f32,
            use_duration_ticks: 32,
            always_edible: false,
            return_item: None,
        }),
    },
    // CookedPorkchop = 74
    ItemDef {
        name: "Cooked Porkchop",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (7, 11),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: Some(FoodProperties {
            hunger: 8f32,
            saturation: 12.8f32,
            use_duration_ticks: 32,
            always_edible: false,
            return_item: None,
        }),
    },
    // RawBeef = 75
    ItemDef {
        name: "Raw Beef",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (4, 11),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: Some(FoodProperties {
            hunger: 3f32,
            saturation: 1.8f32,
            use_duration_ticks: 32,
            always_edible: false,
            return_item: None,
        }),
    },
    // CookedBeef = 76
    ItemDef {
        name: "Cooked Beef",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (8, 11),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: Some(FoodProperties {
            hunger: 8f32,
            saturation: 12.8f32,
            use_duration_ticks: 32,
            always_edible: false,
            return_item: None,
        }),
    },
    // RawMutton = 77
    ItemDef {
        name: "Raw Mutton",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (5, 11),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: Some(FoodProperties {
            hunger: 2f32,
            saturation: 1.2f32,
            use_duration_ticks: 32,
            always_edible: false,
            return_item: None,
        }),
    },
    // CookedMutton = 78
    ItemDef {
        name: "Cooked Mutton",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (9, 11),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: Some(FoodProperties {
            hunger: 6f32,
            saturation: 9.6f32,
            use_duration_ticks: 32,
            always_edible: false,
            return_item: None,
        }),
    },
    // RawChicken = 79
    ItemDef {
        name: "Raw Chicken",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (6, 11),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: Some(FoodProperties {
            hunger: 2f32,
            saturation: 1.2f32,
            use_duration_ticks: 32,
            always_edible: false,
            return_item: None,
        }),
    },
    // CookedChicken = 80
    ItemDef {
        name: "Cooked Chicken",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (10, 11),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: Some(FoodProperties {
            hunger: 6f32,
            saturation: 7.2f32,
            use_duration_ticks: 32,
            always_edible: false,
            return_item: None,
        }),
    },
    // Wool = 81
    ItemDef {
        name: "Wool Block",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Snow),
        tex_coords: (10, 11),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // Leather = 82
    ItemDef {
        name: "Leather",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (11, 11),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // Feather = 83
    ItemDef {
        name: "Feather",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (12, 11),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // Egg = 84
    ItemDef {
        name: "Egg",
        max_stack: 16,
        is_block: false,
        block_type: None,
        tex_coords: (13, 11),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: None,
    },
    // RedDye = 85
    ItemDef {
        name: "Red Dye",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (14, 11),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // BlueDye = 86
    ItemDef {
        name: "Blue Dye",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (15, 11),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // GreenDye = 87
    ItemDef {
        name: "Green Dye",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (15, 11),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // BirchLog = 88
    ItemDef {
        name: "Birch Log",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::BirchLog),
        tex_coords: (1, 12),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // BirchPlanks = 89
    ItemDef {
        name: "Birch Planks",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::BirchPlanks),
        tex_coords: (2, 12),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // BirchLeaves = 90
    ItemDef {
        name: "Birch Leaves",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::BirchLeaves),
        tex_coords: (3, 12),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // SpruceLog = 91
    ItemDef {
        name: "Spruce Log",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::SpruceLog),
        tex_coords: (5, 12),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // SprucePlanks = 92
    ItemDef {
        name: "Spruce Planks",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::SprucePlanks),
        tex_coords: (6, 12),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // SpruceLeaves = 93
    ItemDef {
        name: "Spruce Leaves",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::SpruceLeaves),
        tex_coords: (7, 12),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // TallGrass = 94
    ItemDef {
        name: "Tall Grass",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::TallGrass),
        tex_coords: (8, 12),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // Dandelion = 95
    ItemDef {
        name: "Dandelion",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Dandelion),
        tex_coords: (9, 12),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // Poppy = 96
    ItemDef {
        name: "Poppy",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Poppy),
        tex_coords: (10, 12),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // Cactus = 97
    ItemDef {
        name: "Cactus",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Cactus),
        tex_coords: (11, 12),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // SugarCane = 98
    ItemDef {
        name: "Sugar Cane",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::SugarCane),
        tex_coords: (12, 12),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // Pumpkin = 99
    ItemDef {
        name: "Pumpkin",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Pumpkin),
        tex_coords: (13, 12),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // Melon = 100
    ItemDef {
        name: "Melon",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Melon),
        tex_coords: (14, 12),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // EnchantingTable = 101
    ItemDef {
        name: "Enchanting Table",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::EnchantingTable),
        tex_coords: (0, 13),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // BrewingStand = 102
    ItemDef {
        name: "Brewing Stand",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::BrewingStand),
        tex_coords: (1, 13),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // Anvil = 103
    ItemDef {
        name: "Anvil",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Anvil),
        tex_coords: (2, 13),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // LapisLazuli = 104
    ItemDef {
        name: "Lapis Lazuli",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (3, 13),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // IronHelmet = 105
    ItemDef {
        name: "Iron Helmet",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (4, 13),
        creative_tab: Some(CreativeTab::Combat),
        tool: None,
        armor: Some(ArmorProperties {
            slot: ArmorSlot::Helmet,
            armor_points: 2f32,
            toughness: 0f32,
            knockback_resistance: 0f32,
            durability: 165,
        }),
        food: None,
    },
    // IronChestplate = 106
    ItemDef {
        name: "Iron Chestplate",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (5, 13),
        creative_tab: Some(CreativeTab::Combat),
        tool: None,
        armor: Some(ArmorProperties {
            slot: ArmorSlot::Chestplate,
            armor_points: 6f32,
            toughness: 0f32,
            knockback_resistance: 0f32,
            durability: 240,
        }),
        food: None,
    },
    // IronLeggings = 107
    ItemDef {
        name: "Iron Leggings",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (6, 13),
        creative_tab: Some(CreativeTab::Combat),
        tool: None,
        armor: Some(ArmorProperties {
            slot: ArmorSlot::Leggings,
            armor_points: 5f32,
            toughness: 0f32,
            knockback_resistance: 0f32,
            durability: 225,
        }),
        food: None,
    },
    // IronBoots = 108
    ItemDef {
        name: "Iron Boots",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (7, 13),
        creative_tab: Some(CreativeTab::Combat),
        tool: None,
        armor: Some(ArmorProperties {
            slot: ArmorSlot::Boots,
            armor_points: 2f32,
            toughness: 0f32,
            knockback_resistance: 0f32,
            durability: 195,
        }),
        food: None,
    },
    // GlassBottle = 109
    ItemDef {
        name: "Glass Bottle",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (8, 13),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: None,
    },
    // Potion = 110
    ItemDef {
        name: "Potion",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (9, 13),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: None,
    },
    // SplashPotion = 111
    ItemDef {
        name: "Splash Potion",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (10, 13),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: None,
    },
    // NetherWart = 112
    ItemDef {
        name: "Nether Wart",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (11, 13),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: None,
    },
    // Sugar = 113
    ItemDef {
        name: "Sugar",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (12, 13),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: None,
    },
    // BlazePowder = 114
    ItemDef {
        name: "Blaze Powder",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (13, 13),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: None,
    },
    // GlisteringMelon = 115
    ItemDef {
        name: "Glistering Melon",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (14, 13),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: None,
    },
    // GhastTear = 116
    ItemDef {
        name: "Ghast Tear",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (15, 13),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: None,
    },
    // GoldenCarrot = 117
    ItemDef {
        name: "Golden Carrot",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (0, 14),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: Some(FoodProperties {
            hunger: 6f32,
            saturation: 14.4f32,
            use_duration_ticks: 32,
            always_edible: false,
            return_item: None,
        }),
    },
    // FermentedSpiderEye = 118
    ItemDef {
        name: "Fermented Spider Eye",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (1, 14),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: None,
    },
    // MagmaCream = 119
    ItemDef {
        name: "Magma Cream",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (2, 14),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: None,
    },
    // Pufferfish = 120
    ItemDef {
        name: "Pufferfish",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (3, 14),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: None,
    },
    // SpiderEye = 121
    ItemDef {
        name: "Spider Eye",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (4, 14),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: None,
    },
    // GlowstoneDust = 122
    ItemDef {
        name: "Glowstone Dust",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (5, 14),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: None,
    },
    // RedstoneDust = 123
    ItemDef {
        name: "Redstone Dust",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (6, 14),
        creative_tab: Some(CreativeTab::FoodAndBrewing),
        tool: None,
        armor: None,
        food: None,
    },
    // Arrow = 124
    ItemDef {
        name: "Arrow",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (7, 14),
        creative_tab: Some(CreativeTab::Combat),
        tool: None,
        armor: None,
        food: None,
    },
    // RedstoneWire = 125
    ItemDef {
        name: "Redstone Wire",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::RedstoneWire),
        tex_coords: (5, 2),
        creative_tab: Some(CreativeTab::Redstone),
        tool: None,
        armor: None,
        food: None,
    },
    // RedstoneTorch = 126
    ItemDef {
        name: "Redstone Torch",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::RedstoneTorch),
        tex_coords: (6, 2),
        creative_tab: Some(CreativeTab::Redstone),
        tool: None,
        armor: None,
        food: None,
    },
    // Repeater = 127
    ItemDef {
        name: "Redstone Repeater",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Repeater),
        tex_coords: (7, 2),
        creative_tab: Some(CreativeTab::Redstone),
        tool: None,
        armor: None,
        food: None,
    },
    // Comparator = 128
    ItemDef {
        name: "Redstone Comparator",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Comparator),
        tex_coords: (8, 2),
        creative_tab: Some(CreativeTab::Redstone),
        tool: None,
        armor: None,
        food: None,
    },
    // StoneButton = 129
    ItemDef {
        name: "Stone Button",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::StoneButton),
        tex_coords: (9, 2),
        creative_tab: Some(CreativeTab::Redstone),
        tool: None,
        armor: None,
        food: None,
    },
    // Lever = 130
    ItemDef {
        name: "Lever",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Lever),
        tex_coords: (10, 2),
        creative_tab: Some(CreativeTab::Redstone),
        tool: None,
        armor: None,
        food: None,
    },
    // PressurePlate = 131
    ItemDef {
        name: "Stone Pressure Plate",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::PressurePlate),
        tex_coords: (11, 2),
        creative_tab: Some(CreativeTab::Redstone),
        tool: None,
        armor: None,
        food: None,
    },
    // Piston = 132
    ItemDef {
        name: "Piston",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Piston),
        tex_coords: (12, 2),
        creative_tab: Some(CreativeTab::Redstone),
        tool: None,
        armor: None,
        food: None,
    },
    // StickyPiston = 133
    ItemDef {
        name: "Sticky Piston",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::StickyPiston),
        tex_coords: (13, 2),
        creative_tab: Some(CreativeTab::Redstone),
        tool: None,
        armor: None,
        food: None,
    },
    // RedstoneLamp = 134
    ItemDef {
        name: "Redstone Lamp",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::RedstoneLamp),
        tex_coords: (14, 2),
        creative_tab: Some(CreativeTab::Redstone),
        tool: None,
        armor: None,
        food: None,
    },
    // OakDoor = 135
    ItemDef {
        name: "Oak Door",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::OakDoor),
        tex_coords: (9, 14),
        creative_tab: Some(CreativeTab::Redstone),
        tool: None,
        armor: None,
        food: None,
    },
    // OakTrapdoor = 136
    ItemDef {
        name: "Oak Trapdoor",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::OakTrapdoor),
        tex_coords: (10, 14),
        creative_tab: Some(CreativeTab::Redstone),
        tool: None,
        armor: None,
        food: None,
    },
    // Dispenser = 137
    ItemDef {
        name: "Dispenser",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Dispenser),
        tex_coords: (11, 14),
        creative_tab: Some(CreativeTab::Redstone),
        tool: None,
        armor: None,
        food: None,
    },
    // Dropper = 138
    ItemDef {
        name: "Dropper",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Dropper),
        tex_coords: (12, 14),
        creative_tab: Some(CreativeTab::Redstone),
        tool: None,
        armor: None,
        food: None,
    },
    // NoteBlock = 139
    ItemDef {
        name: "Note Block",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::NoteBlock),
        tex_coords: (13, 14),
        creative_tab: Some(CreativeTab::Redstone),
        tool: None,
        armor: None,
        food: None,
    },
    // Netherrack = 140
    ItemDef {
        name: "Netherrack",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Netherrack),
        tex_coords: (10, 15),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // SoulSand = 141
    ItemDef {
        name: "Soul Sand",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::SoulSand),
        tex_coords: (11, 15),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // Glowstone = 142
    ItemDef {
        name: "Glowstone",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Glowstone),
        tex_coords: (12, 15),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // EndStone = 143
    ItemDef {
        name: "End Stone",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::EndStone),
        tex_coords: (14, 15),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // EndPortalFrame = 144
    ItemDef {
        name: "End Portal Frame",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::EndPortalFrame),
        tex_coords: (15, 15),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // Purpur = 145
    ItemDef {
        name: "Purpur Block",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Purpur),
        tex_coords: (15, 10),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // DragonEgg = 146
    ItemDef {
        name: "Dragon Egg",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::DragonEgg),
        tex_coords: (14, 11),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // WitherSkeletonSkull = 147
    ItemDef {
        name: "Wither Skeleton Skull",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::WitherSkeletonSkull),
        tex_coords: (15, 11),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // NetherBrick = 148
    ItemDef {
        name: "Nether Bricks",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::NetherBrick),
        tex_coords: (9, 10),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // FlintAndSteel = 149
    ItemDef {
        name: "Flint and Steel",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (11, 10),
        creative_tab: Some(CreativeTab::Tools),
        tool: None,
        armor: None,
        food: None,
    },
    // EyeOfEnder = 150
    ItemDef {
        name: "Eye of Ender",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (12, 10),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // Elytra = 151
    ItemDef {
        name: "Elytra",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (13, 10),
        creative_tab: Some(CreativeTab::Tools),
        tool: None,
        armor: None,
        food: None,
    },
    // NetherStar = 152
    ItemDef {
        name: "Nether Star",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (3, 4),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // EndCrystal = 153
    ItemDef {
        name: "End Crystal",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (4, 4),
        creative_tab: Some(CreativeTab::Combat),
        tool: None,
        armor: None,
        food: None,
    },
    // BlazeRod = 154
    ItemDef {
        name: "Blaze Rod",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (5, 4),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // ShulkerShell = 155
    ItemDef {
        name: "Shulker Shell",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (14, 14),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // OakSlab = 156
    ItemDef {
        name: "Oak Slab",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::OakSlab),
        tex_coords: (6, 0),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // CobblestoneSlab = 157
    ItemDef {
        name: "Cobblestone Slab",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::CobblestoneSlab),
        tex_coords: (8, 0),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // OakStair = 158
    ItemDef {
        name: "Oak Stairs",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::OakStair),
        tex_coords: (6, 0),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // CobblestoneStair = 159
    ItemDef {
        name: "Cobblestone Stairs",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::CobblestoneStair),
        tex_coords: (8, 0),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // OakFence = 160
    ItemDef {
        name: "Oak Fence",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::OakFence),
        tex_coords: (6, 0),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // OakFenceGate = 161
    ItemDef {
        name: "Oak Fence Gate",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::OakFenceGate),
        tex_coords: (6, 0),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // CobblestoneWall = 162
    ItemDef {
        name: "Cobblestone Wall",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::CobblestoneWall),
        tex_coords: (8, 0),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // GlassPane = 163
    ItemDef {
        name: "Glass Pane",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::GlassPane),
        tex_coords: (0, 1),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // OakLadder = 164
    ItemDef {
        name: "Ladder",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::OakLadder),
        tex_coords: (3, 5),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // OakSign = 165
    ItemDef {
        name: "Oak Sign",
        max_stack: 16,
        is_block: true,
        block_type: Some(BlockType::OakSign),
        tex_coords: (6, 0),
        creative_tab: Some(CreativeTab::Blocks),
        tool: None,
        armor: None,
        food: None,
    },
    // WoodenSword = 166
    ItemDef {
        name: "Wooden Sword",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (0, 7),
        creative_tab: Some(CreativeTab::Combat),
        tool: Some(ToolProperties {
            tool_type: ToolType::Sword,
            material: ToolMaterial::Wood,
            mining_speed: 2f32,
            durability: 59,
            damage: 4f32,
        }),
        armor: None,
        food: None,
    },
    // WoodenPickaxe = 167
    ItemDef {
        name: "Wooden Pickaxe",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (0, 6),
        creative_tab: Some(CreativeTab::Combat),
        tool: Some(ToolProperties {
            tool_type: ToolType::Pickaxe,
            material: ToolMaterial::Wood,
            mining_speed: 2f32,
            durability: 59,
            damage: 2f32,
        }),
        armor: None,
        food: None,
    },
    // WoodenAxe = 168
    ItemDef {
        name: "Wooden Axe",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (0, 5),
        creative_tab: Some(CreativeTab::Combat),
        tool: Some(ToolProperties {
            tool_type: ToolType::Axe,
            material: ToolMaterial::Wood,
            mining_speed: 2f32,
            durability: 59,
            damage: 7f32,
        }),
        armor: None,
        food: None,
    },
    // WoodenShovel = 169
    ItemDef {
        name: "Wooden Shovel",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (0, 4),
        creative_tab: Some(CreativeTab::Combat),
        tool: Some(ToolProperties {
            tool_type: ToolType::Shovel,
            material: ToolMaterial::Wood,
            mining_speed: 2f32,
            durability: 59,
            damage: 2.5f32,
        }),
        armor: None,
        food: None,
    },
    // GoldenSword = 170
    ItemDef {
        name: "Golden Sword",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (4, 7),
        creative_tab: Some(CreativeTab::Combat),
        tool: Some(ToolProperties {
            tool_type: ToolType::Sword,
            material: ToolMaterial::Gold,
            mining_speed: 12f32,
            durability: 32,
            damage: 4f32,
        }),
        armor: None,
        food: None,
    },
    // GoldenPickaxe = 171
    ItemDef {
        name: "Golden Pickaxe",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (4, 6),
        creative_tab: Some(CreativeTab::Combat),
        tool: Some(ToolProperties {
            tool_type: ToolType::Pickaxe,
            material: ToolMaterial::Gold,
            mining_speed: 12f32,
            durability: 32,
            damage: 2f32,
        }),
        armor: None,
        food: None,
    },
    // GoldenAxe = 172
    ItemDef {
        name: "Golden Axe",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (4, 5),
        creative_tab: Some(CreativeTab::Combat),
        tool: Some(ToolProperties {
            tool_type: ToolType::Axe,
            material: ToolMaterial::Gold,
            mining_speed: 12f32,
            durability: 32,
            damage: 7f32,
        }),
        armor: None,
        food: None,
    },
    // GoldenShovel = 173
    ItemDef {
        name: "Golden Shovel",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (4, 4),
        creative_tab: Some(CreativeTab::Combat),
        tool: Some(ToolProperties {
            tool_type: ToolType::Shovel,
            material: ToolMaterial::Gold,
            mining_speed: 12f32,
            durability: 32,
            damage: 2.5f32,
        }),
        armor: None,
        food: None,
    },
    // LeatherHelmet = 174
    ItemDef {
        name: "Leather Cap",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (0, 13),
        creative_tab: Some(CreativeTab::Combat),
        tool: None,
        armor: Some(ArmorProperties {
            slot: ArmorSlot::Helmet,
            armor_points: 1f32,
            toughness: 0f32,
            knockback_resistance: 0f32,
            durability: 55,
        }),
        food: None,
    },
    // LeatherChestplate = 175
    ItemDef {
        name: "Leather Tunic",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (0, 14),
        creative_tab: Some(CreativeTab::Combat),
        tool: None,
        armor: Some(ArmorProperties {
            slot: ArmorSlot::Chestplate,
            armor_points: 3f32,
            toughness: 0f32,
            knockback_resistance: 0f32,
            durability: 80,
        }),
        food: None,
    },
    // LeatherLeggings = 176
    ItemDef {
        name: "Leather Pants",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (0, 15),
        creative_tab: Some(CreativeTab::Combat),
        tool: None,
        armor: Some(ArmorProperties {
            slot: ArmorSlot::Leggings,
            armor_points: 2f32,
            toughness: 0f32,
            knockback_resistance: 0f32,
            durability: 75,
        }),
        food: None,
    },
    // LeatherBoots = 177
    ItemDef {
        name: "Leather Boots",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (0, 12),
        creative_tab: Some(CreativeTab::Combat),
        tool: None,
        armor: Some(ArmorProperties {
            slot: ArmorSlot::Boots,
            armor_points: 1f32,
            toughness: 0f32,
            knockback_resistance: 0f32,
            durability: 65,
        }),
        food: None,
    },
    // GoldenHelmet = 178
    ItemDef {
        name: "Golden Helmet",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (3, 13),
        creative_tab: Some(CreativeTab::Combat),
        tool: None,
        armor: Some(ArmorProperties {
            slot: ArmorSlot::Helmet,
            armor_points: 2f32,
            toughness: 0f32,
            knockback_resistance: 0f32,
            durability: 77,
        }),
        food: None,
    },
    // GoldenChestplate = 179
    ItemDef {
        name: "Golden Chestplate",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (3, 14),
        creative_tab: Some(CreativeTab::Combat),
        tool: None,
        armor: Some(ArmorProperties {
            slot: ArmorSlot::Chestplate,
            armor_points: 5f32,
            toughness: 0f32,
            knockback_resistance: 0f32,
            durability: 112,
        }),
        food: None,
    },
    // GoldenLeggings = 180
    ItemDef {
        name: "Golden Leggings",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (3, 15),
        creative_tab: Some(CreativeTab::Combat),
        tool: None,
        armor: Some(ArmorProperties {
            slot: ArmorSlot::Leggings,
            armor_points: 3f32,
            toughness: 0f32,
            knockback_resistance: 0f32,
            durability: 105,
        }),
        food: None,
    },
    // GoldenBoots = 181
    ItemDef {
        name: "Golden Boots",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (3, 12),
        creative_tab: Some(CreativeTab::Combat),
        tool: None,
        armor: Some(ArmorProperties {
            slot: ArmorSlot::Boots,
            armor_points: 1f32,
            toughness: 0f32,
            knockback_resistance: 0f32,
            durability: 91,
        }),
        food: None,
    },
    // DiamondHelmet = 182
    ItemDef {
        name: "Diamond Helmet",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (2, 13),
        creative_tab: Some(CreativeTab::Combat),
        tool: None,
        armor: Some(ArmorProperties {
            slot: ArmorSlot::Helmet,
            armor_points: 3f32,
            toughness: 2f32,
            knockback_resistance: 0f32,
            durability: 363,
        }),
        food: None,
    },
    // DiamondChestplate = 183
    ItemDef {
        name: "Diamond Chestplate",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (2, 14),
        creative_tab: Some(CreativeTab::Combat),
        tool: None,
        armor: Some(ArmorProperties {
            slot: ArmorSlot::Chestplate,
            armor_points: 8f32,
            toughness: 2f32,
            knockback_resistance: 0f32,
            durability: 528,
        }),
        food: None,
    },
    // DiamondLeggings = 184
    ItemDef {
        name: "Diamond Leggings",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (2, 15),
        creative_tab: Some(CreativeTab::Combat),
        tool: None,
        armor: Some(ArmorProperties {
            slot: ArmorSlot::Leggings,
            armor_points: 6f32,
            toughness: 2f32,
            knockback_resistance: 0f32,
            durability: 495,
        }),
        food: None,
    },
    // DiamondBoots = 185
    ItemDef {
        name: "Diamond Boots",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (2, 12),
        creative_tab: Some(CreativeTab::Combat),
        tool: None,
        armor: Some(ArmorProperties {
            slot: ArmorSlot::Boots,
            armor_points: 3f32,
            toughness: 2f32,
            knockback_resistance: 0f32,
            durability: 429,
        }),
        food: None,
    },
    // Shield = 186
    ItemDef {
        name: "Shield",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (15, 12),
        creative_tab: Some(CreativeTab::Combat),
        tool: None,
        armor: None,
        food: None,
    },
    // Saddle = 187
    ItemDef {
        name: "Saddle",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (8, 6),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // Emerald = 188
    ItemDef {
        name: "Emerald",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (11, 1),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // Book = 189
    ItemDef {
        name: "Book",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (11, 3),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // Paper = 190
    ItemDef {
        name: "Paper",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (10, 3),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // EnchantedBook = 191
    ItemDef {
        name: "Enchanted Book",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (11, 3),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // Compass = 192
    ItemDef {
        name: "Compass",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (6, 3),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // String = 193
    ItemDef {
        name: "String",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (8, 3),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // Slimeball = 194
    ItemDef {
        name: "Slimeball",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (14, 1),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // RawCod = 195
    ItemDef {
        name: "Raw Cod",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (1, 10),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // RawSalmon = 196
    ItemDef {
        name: "Raw Salmon",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (2, 10),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // InkSac = 197
    ItemDef {
        name: "Ink Sac",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (15, 1),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // OakBoat = 198
    ItemDef {
        name: "Oak Boat",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (8, 6),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // Minecart = 199
    ItemDef {
        name: "Minecart",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (8, 7),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // Rail = 200
    ItemDef {
        name: "Rail",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Rail),
        tex_coords: (0, 8),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // PoweredRail = 201
    ItemDef {
        name: "Powered Rail",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::PoweredRail),
        tex_coords: (3, 8),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // DetectorRail = 202
    ItemDef {
        name: "Detector Rail",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::DetectorRail),
        tex_coords: (3, 9),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // ActivatorRail = 203
    ItemDef {
        name: "Activator Rail",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::ActivatorRail),
        tex_coords: (3, 10),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // Clock = 204
    ItemDef {
        name: "Clock",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (8, 4),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // Map = 205
    ItemDef {
        name: "Map",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (8, 5),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // FishingRod = 206
    ItemDef {
        name: "Fishing Rod",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (5, 4),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // RawFish = 207
    ItemDef {
        name: "Raw Fish",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (1, 10),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // TropicalFish = 208
    ItemDef {
        name: "Tropical Fish",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (3, 10),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // LilyPad = 209
    ItemDef {
        name: "Lily Pad",
        max_stack: 64,
        is_block: false,
        block_type: None,
        tex_coords: (12, 0),
        creative_tab: Some(CreativeTab::Misc),
        tool: None,
        armor: None,
        food: None,
    },
    // WaterBucket = 210
    ItemDef {
        name: "Water Bucket",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (1, 11),
        creative_tab: Some(CreativeTab::Tools),
        tool: None,
        armor: None,
        food: None,
    },
    // LavaBucket = 211
    ItemDef {
        name: "Lava Bucket",
        max_stack: 1,
        is_block: false,
        block_type: None,
        tex_coords: (1, 11),
        creative_tab: Some(CreativeTab::Tools),
        tool: None,
        armor: None,
        food: None,
    },
    // Hopper = 212
    ItemDef {
        name: "Hopper",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Hopper),
        tex_coords: (11, 15),
        creative_tab: Some(CreativeTab::Redstone),
        tool: None,
        armor: None,
        food: None,
    },
    // Observer = 213
    ItemDef {
        name: "Observer",
        max_stack: 64,
        is_block: true,
        block_type: Some(BlockType::Observer),
        tex_coords: (11, 16),
        creative_tab: Some(CreativeTab::Redstone),
        tool: None,
        armor: None,
        food: None,
    },
];
